### ISSUE TITLE
dragula_1.default is not a function

### ISSUE THREAD

**Issue by sga-lalitesh** [cormacrelf/dragula-touch-demo#1]
I'm facing this issue in my angular4 application.
Import section
`import {DragulaService} from 'ng2-dragula/ng2-dragula';
import dragula from 'dragula';
import autoScroll from 'dom-autoscroller';`

`ngOnInit() {
        // create the drake manually so we can refer to it's dragging property
        let drake = dragula();
        this.dragulaService.add('STOP_BAG', drake);

        this.scroll = autoScroll(
          window,
          {
            margin: 30,
            maxSpeed: 25,
            scrollWhenOutside: true,
              
            autoScroll: function () {
              return this.down && drake.dragging;
            }
          });
      }`

**Comment by cormacrelf** [comment]
Install dragula please.

**Comment by sga-lalitesh** [comment]
Dragula is installed in my repo.
I can see the dragula.js in node_modules. But still the error is there....

**Comment by cormacrelf** [comment]
This repo worked when I built it. Fix it yourself. Sorry.

**Comment by KEMBL** [comment]
try to import dragula and  autoScroll like that:

`import * as dragula from 'dragula';`

`import * as autoScroll from 'dom-autoscroller';`

also applicable for #5
