### ISSUE TITLE
How to use this with webpack

### ISSUE THREAD

**Issue by sga-lalitesh** [cormacrelf/dragula-touch-demo#2]
Can you help me in using this with webpack

**Comment by cormacrelf** [comment]
It is no different than using the CLI. The CLI uses webpack under the hood, anyway.

**Comment by sga-lalitesh** [comment]
In my code its showing the error:
dragula_1.default is not a function

If I use this line
import {dragula, DragulaService} from 'ng2-dragula/ng2-dragula';

this error removes and next error appears

dom_autoscroll_1.default is not a function

I check the browser, dragula.js is available there with module.export = dragula

but these errors are still visible on the console.

I clone your repo, its working fine on my machine.

**Comment by cormacrelf** [comment]
This repo is not maintained software, a library, or a demo for how to configure Webpack and NPM. It is merely a guide to using ng2-dragula with a couple of extra niceties.

Please figure this out yourself.
